knpu_oauth2_client:
    clients:
        facebook:
            type: facebook
            client_id: '%env(FACEBOOK_CLIENT_ID)%'
            client_secret: '%env(FACEBOOK_CLIENT_SECRET)%'
            redirect_route: oauth_login_facebook_callback
            redirect_params: { }
            graph_api_version: v2.12
