version: '3'

services:

    nginx:
        image: ${DOCKER_REGISTRY}/nginx:${IMAGE_TAG}
        restart: always
        ports:
            - "8080:80"
        depends_on:
            - php-fpm

    php-fpm:
        image: ${DOCKER_REGISTRY}/php-fpm:${IMAGE_TAG}
        restart: always
        env_file:
            - docker-compose.env
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
  mysql:
      driver: local
